name: Generate Resume

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-lang-japanese fonts-noto-cjk
        
    - name: Generate combined markdown
      run: |
        echo "# 職務経歴書" > combined-resume.md
        echo "" >> combined-resume.md
        echo "_**生成日**: $(date '+%Y年%m月%d日')_" >> combined-resume.md
        echo "" >> combined-resume.md
        
        # README.mdの内容を追加（docs/へのリンク部分は除外）
        tail -n +2 README.md | sed '/\*\*詳細情報\*\*:/d' >> combined-resume.md
        echo "" >> combined-resume.md
        
        # 各詳細ファイルの内容を追加
        if [ -f "docs/S社_AI連携企業材料データベース検索システム.md" ]; then
          echo "---" >> combined-resume.md
          echo "" >> combined-resume.md
          echo "# S社 詳細情報" >> combined-resume.md
          echo "" >> combined-resume.md
          cat "docs/S社_AI連携企業材料データベース検索システム.md" >> combined-resume.md
          echo "" >> combined-resume.md
        fi
        
        if [ -f "docs/C社_AI音声プラットフォーム開発.md" ]; then
          echo "---" >> combined-resume.md
          echo "" >> combined-resume.md
          echo "# C社 詳細情報" >> combined-resume.md
          echo "" >> combined-resume.md
          cat "docs/C社_AI音声プラットフォーム開発.md" >> combined-resume.md
          echo "" >> combined-resume.md
        fi
        
        if [ -f "docs/I社_統合ログ管理システム.md" ]; then
          echo "---" >> combined-resume.md
          echo "" >> combined-resume.md
          echo "# I社 詳細情報" >> combined-resume.md
          echo "" >> combined-resume.md
          cat "docs/I社_統合ログ管理システム.md" >> combined-resume.md
          echo "" >> combined-resume.md
        fi
        
        if [ -f "docs/U社_BtoB営業支援SaaS.md" ]; then
          echo "---" >> combined-resume.md
          echo "" >> combined-resume.md
          echo "# U社 詳細情報" >> combined-resume.md
          echo "" >> combined-resume.md
          cat "docs/U社_BtoB営業支援SaaS.md" >> combined-resume.md
          echo "" >> combined-resume.md
        fi
        
        if [ -f "docs/H社_オフィス家具受発注システム.md" ]; then
          echo "---" >> combined-resume.md
          echo "" >> combined-resume.md
          echo "# H社 詳細情報" >> combined-resume.md
          echo "" >> combined-resume.md
          cat "docs/H社_オフィス家具受発注システム.md" >> combined-resume.md
          echo "" >> combined-resume.md
        fi
    
    - name: Generate HTML
      run: |
        # HTML 생성 (기본 스타일 사용)
        pandoc combined-resume.md -o resume-complete.html \
          --standalone \
          --metadata title="職務経歴書 - 黄 丞涓（ファン スンヨン）" \
          --metadata lang=ja \
          --toc \
          --toc-depth=2 \
          --from=markdown+raw_html
    
    - name: Generate PDF
      run: |
        # PDF 생성 (XeLaTeX 사용, 일본어 폰트 지원)
        pandoc combined-resume.md -o resume-complete.pdf \
          --pdf-engine=xelatex \
          --variable mainfont="Noto Sans CJK JP" \
          --variable papersize=a4 \
          --variable geometry:margin=2cm \
          --toc \
          --toc-depth=2
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume-files
        path: |
          combined-resume.md
          resume-complete.html
          resume-complete.pdf
    
    - name: Create Release (if tagged)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          combined-resume.md
          resume-complete.html
          resume-complete.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}